### ISSUE TITLE
Add Kitty port

### ISSUE THREAD

**Issue by rsaihe** [sainnhe/sonokai#1]
I just found this theme and I quickly whipped up a port of it for Kitty [here](https://github.com/rsaihe/sonokai-kitty), in case you want to link it or anything else.

**Comment by sainnhe** [comment]
Wow, great work! Thanks!

**Comment by sainnhe** [comment]
It's now metioned in [readme](https://github.com/sainnhe/sonokai#related-projects). I'm also going to add some ports later.
