### ISSUE TITLE
MDX support

### ISSUE THREAD

**Issue by dakahn** [sainnhe/sonokai#10]
- Operating system/version: WSL 2 in Windows Terminal
- Terminal emulator/version: Windows Terminal 1.2.2381.0
- `echo $TERM`: xterm-256color
- `vim --version` or `nvim --version`: v0.4.3

First and foremost I wanted to say that you've done a fantastic job here. Thank you! 🎉
 
Support for MDX files using package [vim-mdx-js](https://github.com/jxnblk/vim-mdx-js) seems a bit broken (primarily the imports and component tags):
![image](https://user-images.githubusercontent.com/40970507/93535981-af59a400-f90d-11ea-9c75-c5d2ac649377.png)

**Comment by sainnhe** [comment]
I just tried it and looks like there is no highlight groups matched code like `import`, I'm not sure how can I fix this in color scheme level. Maybe you can open an issue in [vim-mdx-js](https://github.com/jxnblk/vim-mdx-js/issues).

**Comment by dakahn** [comment]
You're probably spot on on this being their problem. I'll close this up :D
