### ISSUE TITLE
[Question] sonokai_better_performance and `after/syntax`

### ISSUE THREAD

**Issue by Geobert** [sainnhe/sonokai#103]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

Windows 11

### GUI client/version

neovide 

### Feature matrix

N/A

### Minimal vimrc that can reproduce this bug.

N/A

### Steps to reproduce this bug using minimal vimrc

N/A

### Expected behavior

N/A

### Actual behavior

Sorry for hijacking the bug form to ask a question but I couldn’t find a place to ask as the Discution section is not active.

I’m new to nvim and using LazyVim. I’ve installed sonokai which I love, but I don’t understand this part of the doc:
https://github.com/sainnhe/sonokai/blob/master/doc/sonokai.txt#L482

What do we need to put in `after/syntax` and what for?

**Comment by antoineco** [comment]
The `after` directory is a built-in Vim feature which Sonokai leverages to provide the "better performance" mode.
It allows loading configuration files or plugins after the default Vim configuration has been loaded.

The good news is that **you don't need to do anything with this directory yourself**. Sonokai will populate it with files called `c.vim`, `python.vim`, `java.vim`, etc. corresponding to each of the file types supported by the colorscheme.

I suggest looking into this thread to learn more about the `after` directory: https://www.reddit.com/r/neovim/comments/x3zp6t/usage_of_afterftplugin_directory_for/

**Comment by Geobert** [comment]
Thanks a lot it makes perfect sense!
