### ISSUE TITLE
Neovim Treesitter and LSP support?

### ISSUE THREAD

**Issue by carlitux** [sainnhe/sonokai#14]

**Comment by carlitux** [comment]
Hi,

Would like to have the support for these two features

Thanks.

**Comment by sainnhe** [comment]
Isn't it already supported? Bug report is welcome.

**Comment by carlitux** [comment]
Sorry, I just noticed that it supports.

I thought it should follow colors as other themes but here is grey what makes me keep focusing on code. Thanks!

The only thing I see pending is the underline style.

**Comment by sainnhe** [comment]
> The only thing I see pending is the underline style.

Not sure what you mean by ”underline style”. I just added some new hi groups that tree sitter has supported recently, you can update this color scheme and get it a try.

**Comment by carlitux** [comment]
sorry for vague comments here from another theme https://github.com/Julpikar/night-owl.nvim

![102687084-18a7c680-421f-11eb-99a0-016fcf3027c9](https://user-images.githubusercontent.com/40538/103292618-95c40000-49c4-11eb-9a5f-08b890333326.jpg)

from neovim docs

```
                 vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
                   vim.lsp.diagnostic.on_publish_diagnostics, {
                     -- Enable underline, use default values
                     underline = true,
                     -- Enable virtual text, override spacing to 4
                     virtual_text = {
                       spacing = 4,
                     },
                     -- Use a function to dynamically turn signs off
                     -- and on, using buffer local variables
                     signs = function(bufnr, client_id)
                       return vim.bo[bufnr].show_signs == false
                     end,
                     -- Disable a feature
                     update_in_insert = false,
                   }
                 )
```

lsp diagnostic can be configured to enable or disable the underline under the section where it is the diagnostic message

**Comment by sainnhe** [comment]
Thank you for the feedback, that's a bug, should be fixed via https://github.com/sainnhe/sonokai/commit/00e4199f5aba0dc3c2fefc86500e9ad659fe3fb1.

**Comment by carlitux** [comment]
tested and looks really good, thank you very much!

**Comment by ECon87** [comment]
Hi,

Thank you for the great colorschemes (see gruvbox-material). I am not sure the colorschemes work for R when using the tree-sitter.
They work for python.

What info would you need to file a bug report?

Thank you again.

**Comment by sainnhe** [comment]
@ECon87 Open an issue follow the issue template, also provide the output of ` :checkhealth nvim_treesitter`.
