### ISSUE TITLE
Changing colour of markdown block quotes

### ISSUE THREAD

**Issue by djtsorrell** [sainnhe/sonokai#17]
I've read the docs and found out how I could change the colour of certain highlight groups. I wish to change the colour of markdown block quotes from grey to white. This is what I have in my init.vim
```
if has('termguicolors')
    set termguicolors
endif
let g:sonokai_style = 'shusia'
let g:sonokai_enable_italic = 1
let g:sonokai_diagnostic_line_highlight = 1

function! s:sonokai_custom() abort
    highlight! link markdownBlockquote Grey
    let l:palette = sonokai#get_palette('shusia')
    call sonokai#highlight('Grey', l:palette.fg, l:palette.none)
endfunction

augroup SonokaiCustom
  autocmd!
  autocmd ColorScheme sonokai call s:sonokai_custom()
augroup END

colorscheme sonokai
```
Unfortunately, this hasn't changed the colour of the quotes, but it has changed the colours on Startify (a vim plugin).

**Comment by sainnhe** [comment]
`Grey` is a predefined highlight group, which is linked to many other hi groups, so usually you'd better not to change it.

That's said, you should remove these two lines.

```vim
    let l:palette = sonokai#get_palette('shusia')
    call sonokai#highlight('Grey', l:palette.fg, l:palette.none)
```

---

This line

```vim
highlight! link markdownBlockquote Grey
```

means you linked `markdownBlockquote` to `Grey`, but what you want is to make the markdown block quote white, so you should link this group to another predefined hi group `Fg`.

This should work,  but the premise is that `markdownBlockquote` does decide the color of markdown block quote.

**Comment by djtsorrell** [comment]
Thanks for this. I did try using `Fg` but it didn't change anything. I think this may be a clash with [vim-polyglot](https://github.com/sheerun/vim-polyglot). When I disabled markdown syntax highlighting it changed the block quotes to white!
