### ISSUE TITLE
LSP diagnostics virtual text are all grey

### ISSUE THREAD

**Issue by nkcfan** [sainnhe/sonokai#18]
Hard to differentiate LSP diagnostics virtual text, because they are all grey

https://github.com/sainnhe/sonokai/blob/600d5a0576c363f00611ed611f51a445e6add041/colors/sonokai.vim#L136-L139

- Operating system/version: Linux
- Terminal emulator/version: KiTTY 0.74.4.2 on windows
- `echo $TERM`: tmux-256color
- `tmux -V`: tmux 3.1c
- `vim --version` or `nvim --version`:
NVIM v0.5.0-dev+1115-gc1fbc2ddf

**Comment by sainnhe** [comment]
That's expected, I prefer to use grey virtual text to help me focus on code, and use sign column to distinguish between different diagnostics.

If you prefer colored virtual text, maybe you can try to fork this repository.

**Comment by qiluo-msft** [comment]
Thanks, the latest version works!

**Comment by nkcfan** [comment]
It works now! Thanks!
