### ISSUE TITLE
Color shown as background instead of font color?

### ISSUE THREAD

**Issue by yoonwaiyan** [sainnhe/sonokai#19]
Hello, I may not describe well in the title but here's the screenshot of my code using Sonokai andromeda/default style. Is this normal?

<img width="876" alt="Screenshot 2021-03-30 at 9 45 37 PM" src="https://user-images.githubusercontent.com/3081772/112999148-48148a80-91a1-11eb-893f-975081b703cf.png">
 
You can see my configuration for Sonokai from the screenshot too.

**Comment by sainnhe** [comment]
Because you've enabled italic keywords, but your terminal emulator doesn't support italics. It's similar to this FAQ:

https://github.com/sainnhe/sonokai/blob/78f1b14ad18b043eb888a173f4c431dbf79462d8/doc/sonokai.txt#L365-L372
