### ISSUE TITLE
Separate themes or changing color variants in runtime?

### ISSUE THREAD

**Issue by pechorin** [sainnhe/sonokai#2]
It is not easy to configure and select on runtime different theme variations. Is it possible to change color variant on runtime?

**Comment by sainnhe** [comment]
I prefer to use a global variable to control the color palette.

And of course it's possible to change the variant in runtime, simply execute commands like this:

```
:let g: sonokai_style = 'shusia'
:colo sonokai
```

I'm not going to separate the color schemes. But if you prefer doing that, you can fork this repository and modify the code by yourself.
