### ISSUE TITLE
Why are comments showing up as highlighted blocks?

### ISSUE THREAD

**Issue by githorse** [sainnhe/sonokai#20]
- Operating system/version:
- Terminal emulator/version:
- `echo $TERM`:
- `tmux -V`: 
- `vim --version` or `nvim --version`:

```
Linut Mint 20.1 Ulyssa (Ubuntu 20.04 LTS)
GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
xterm-256color
tmux 3.0a
NVIM v0.4.3
```

### Minimal vimrc that can reproduce this bug

```vim
call plug#begin('~/.vim/plugged')
Plug 'sainnhe/sonokai'
silent! call plug#end()

colorscheme sonokai
```

### Steps to reproduce this bug using minimal vimrc
```
$ vim .vimrc
```

### Actual behaviour
![image](https://user-images.githubusercontent.com/8271372/114603878-40a3b580-9c66-11eb-9839-098c045d59c0.png)

Occurs across all languages.

### Expected behaviour
Nice gray comments like in the pictures :)

**Comment by sainnhe** [comment]
Check FAQ.

**Comment by githorse** [comment]
For anyone else with this issue, found the FAQ [here](https://github.com/sainnhe/sonokai/blob/master/doc/sonokai.txt), under "Usage". After following some links, looks like the [suggested resolutions](https://github.com/sainnhe/gruvbox-material/issues/5) are one or both of:

```
set termguicolors
colorscheme sonokai
```

```
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
colorscheme sonokai
```

in the `.vimrc`. Neither of these resolve the issue for me. But after further research, 

```
let g:sonokai_disable_italic_comment = 1
```

works for me. (Not actually mentioned in the FAQ that I could see.)
