### ISSUE TITLE
Could `sonokai_enable_italic = 1` fail gracefully?

### ISSUE THREAD

**Issue by githorse** [sainnhe/sonokai#21]
### System

```
Linut Mint 20.1 Ulyssa (Ubuntu 20.04 LTS)
GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
xterm-256color
tmux 3.0a
NVIM v0.4.3
```

### Minimal vimrc that can reproduce this bug

```vim
call plug#begin('~/.vim/plugged')
Plug 'sainnhe/sonokai'
silent! call plug#end()

let g:sonokai_enable_italic = 1
colorscheme sonokai
```

![image](https://user-images.githubusercontent.com/8271372/115114097-85c43200-9f5b-11eb-976b-7e17682ebd4d.png)

It took me a while to figure out the blocks of color are occurring because I have `g:sonokai_enable_italic = ` in my `.vimrc` but don't have a font that supports italics. Not a bug exactly, but would it be possible to fail more gracefully so this just looks like normal text?

**Comment by sainnhe** [comment]
That's because your terminal emulator doesn't support italics. Check FAQ, there is something like "Comment color looks weird", which gives a possible solution.
