### ISSUE TITLE
Undercurl shouldn't be disabled for tmux

### ISSUE THREAD

**Issue by kabouzeid** [sainnhe/sonokai#22]
https://github.com/sainnhe/sonokai/blob/764bd716f08f1441e0020b8ae0c8d1b53970e4a9/autoload/sonokai.vim#L163

undercurl is supported by tmux 3, shouldn't be disabled here.

Related: https://github.com/neovim/neovim/pull/9097#issuecomment-825847628

**Comment by sainnhe** [comment]
But it doesn't work in lower versions of tmux

https://github.com/sainnhe/gruvbox-material/issues/29

So what's the minimum version that supports undercurl? I'm going to add version detection then.

**Comment by kabouzeid** [comment]
Pretty sure since 3.0. I couldn't find it in the changelog though.

**Comment by sainnhe** [comment]
I'm not very sure but I found some related issues, looks like this feature is supported in tmux >= 2.9 .

This should be fixed via 784de58.
