### ISSUE TITLE
E5113: Error while calling lua chunk: <path> Vim(return):E121: Undefined variable: palette

### ISSUE THREAD

**Issue by rafamadriz** [sainnhe/sonokai#23]
- Operating system/version: Arch Linux 5.10.32-1-lts 
- Terminal emulator/version: Kitty 0.20.1
- `echo $TERM`: xterm-kitty
- `vim --version` or `nvim --version`: v0.5.0-dev+1282-gfbe18d9ca

```
E5113: Error while calling lua chunk: /home/rafa/.config/nvim/lua/main/colorscheme.lua:21: Vim(return):E121: 
Undefined variable: palette
```
It gives that error and it doesn't set the colorscheme to sonokai, just fells back to neovim builtin default colorscheme.

I have my config in Lua and this is how I'm setting the colorscheme: `vim.cmd("colorscheme sonokai")` And it works with all colorschemes I have, except now for sonokai. Last time I set my colorscheme to sonokai was all working fine.   

![2021-Apr-28](https://user-images.githubusercontent.com/67771985/116457254-ae4d0580-a852-11eb-827b-8afedd1c19d2.png)

**Comment by rafamadriz** [comment]
Okay I just tested with a clean `init.lua` that only has `vim.cmd("colorscheme sonokai")` and it does work, but I don't understand why is it failing to set the colorscheme with sonokai and edge when all of the others colorschemes I have installed are working perfectly fine.

**Comment by sainnhe** [comment]
No one knows what you have done in your init.lua, and that's why I need minimal vimrc to reproduce the bug.

Provide minimal vimrc that can reproduce this bug, or debug it by yourself and try to find out which line caused this bug.

**Comment by sainnhe** [comment]
Closed since I can't reproduce and the user didn't follow the issue template.
