### ISSUE TITLE
Overriding default contrast

### ISSUE THREAD

**Issue by sinetoami** [sainnhe/sonokai#24]
First of all, many thanks for build this plugin so well :1st_place_medal:.

> However there is one thing I can't stand -- the contrast is too high, which is totally unacceptable to me.

It's possible to override the default contrast in some way? If so, how can I do that?

Thanks in advance.

**Comment by sainnhe** [comment]
I adjusted the contrast by modifying the color palettes, so overriding the contrast means you need to modify the color palettes. However, I didn't expose any related APIs, so technically this can't be done via configuration.

Maybe fork this repository and modify the color palettes by yourself.
