### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by kaykhancheckpoint** [sainnhe/sonokai#26]
Hi friends,

I like this theme, i use the default version.

Theres one thing i would like to modify which is the background color. I want it to be a little darker/blacker, can someone tell me if this is pssoble and what command i need to add to my vimrc to make that possible?

**Comment by sainnhe** [comment]
1. Execute `:hi Normal` and check the output.
2. Execute something like `:hi Normal guifg=#ffffff guibg=#000000`.

You should read the help doc of syntax highlighting first.

**Comment by kaykhancheckpoint** [comment]
> 1. Execute `:hi Normal` and check the output.
> 2. Execute something like `:hi Normal guifg=#ffffff guibg=#000000`.
> 
> You should read the help doc of syntax highlighting first.

I tried what you typed but it did not work.

After looking at the docs here - https://elias.rhi.hi.is/vim/syntax.html

It suggests i can run the below command to get a black background with white text. However after applying this in vim it did not have any affect. Could this theme be overriding it?

```
	:highlight Normal guibg=Black guifg=White
```

**Comment by sainnhe** [comment]
Here I suggest 3 way to achieve this:

1. The classic vim way. Take a look at the help doc of syntax highlighting, and put your code in vimrc, the code should typically be placed after `colorscheme sonokai`.
2. See the FAQ of sonokai.txt, there is something like "How to use custom colors?", you can put your code in augroup.
3. Fork this repository and modify `/autoload/sonokai.vim`, change the colors to whatever you like.

---

> I tried what you typed but it did not work.

Did you set true colors?

https://github.com/sainnhe/sonokai/blob/9dd432b1bce0bd448faf22375fcf6311ff0d4226/doc/sonokai.txt#L108-L111

**Comment by kaykhancheckpoint** [comment]
@sainnhe 

I have this in my vimrc

```

if (has("termguicolors") && $TERM_PROGRAM ==# 'iTerm.app')
   set termguicolors
endif

colorscheme sonokai
let g:airline_theme = 'sonokai'
highlight Normal guibg=Black guifg=White
```

Something to note, i found the below code in a differnt plugin, and i noticed if i don't add the second condition this plugin no longer works. (im using tmux).

I found ```
if (has("termguicolors") && $TERM_PROGRAM ==# 'iTerm.app')
   set termguicolors
endif```

**Comment by sainnhe** [comment]
The built-in terminal emulator of mac os is known to unsupport true colors, you can debug it via this:

https://github.com/sainnhe/sonokai/blob/9dd432b1bce0bd448faf22375fcf6311ff0d4226/doc/sonokai.txt#L393

---

If it still doesn't work, I have no idea what's going on and I can't reproduce.

Please follow the issue template to provide detailed information

https://raw.githubusercontent.com/sainnhe/sonokai/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by kaykhancheckpoint** [comment]
Sorry i forgot to mention i am using ubuntu 20.04

**Comment by chaosteil** [comment]
@kaykhancheckpoint Have you tried ctermbg as well?
`:hi Normal ctermbg=Black`

I personally use `hi Normal guibg=none ctermbg=none` in my config after loading all themes

**Comment by kaykhancheckpoint** [comment]
When i switched to neovim it started working.

But you know know customising the color is more difficult than simply setting the `Normal` value. You can see below it still uses the old color in the tree and in other places.

![image](https://user-images.githubusercontent.com/65535942/122357925-11524300-cf4c-11eb-982b-f3d96d053b1a.png)

**Comment by kaykhancheckpoint** [comment]
Ok i managed to fix my problem, unfortunately i had to clone this repo to do it. I wanted to change the bg0 color.

https://github.com/sainnhe/sonokai/blob/master/autoload/sonokai.vim#L62
