### ISSUE TITLE
The matched parenthesis is hard to tell

### ISSUE THREAD

**Issue by yanzhang0219** [sainnhe/sonokai#28]
Been using this color scheme for a long time and I really like it. Thank you.

Just one thing I think needs to improve. The highlight color for the matching parenthesis is very hard to see.

<img width="582" alt="Screen Shot 2021-07-11 at 1 36 52 PM" src="https://user-images.githubusercontent.com/11582667/125209371-266d7980-e24d-11eb-9844-c0c604280b32.png">

Is it possible to improve this? Thank you very much.

**Comment by sainnhe** [comment]
I just tried to use higher contrast but I feel that it doesn't look good ed70043966e20f012a9a7e0d0cb2b5fd203778f3 .

So I'm not going to change the hi group in this color scheme, but you can use configure it in your vimrc instead:

https://github.com/sainnhe/sonokai/blob/ef631befe2bea01c23f4f0d9685025ac15d51ace/doc/sonokai.txt#L429-L461

**Comment by yanzhang0219** [comment]
I got it. Thank you.

**Comment by yanzhang0219** [comment]
Hi,
I have an idea after referring to the solutions of other color scheme. How about marking it with a color along with an underscore?

**Comment by sainnhe** [comment]
I honestly don't want to change it to this, you can install a rainbow parenthesis plugin to help you better distinguish between them.

**Comment by yanzhang0219** [comment]
Okay. Thanks.
