### ISSUE TITLE
Some highlights getting disabled after some time

### ISSUE THREAD

**Issue by TheCharmingSociopath** [sainnhe/sonokai#31]
Short -- Some terms like function names are not highlighted properly in cpp.

When I open a cpp file, some words like function names take some time to get highlighted. It's the ones that are uncoloured in the second image.  The other words are already highlighted, only those specific type of words lag. Then once they are highlighted, after some time as I type, that highlighting goes away and colors go back to the way they were in the first image and then on they are not highlighted anymore. 
I haven't yet noticed this issue with any other file type (could be because I haven't really worked with other languages much recently.) (Aside: The word `Plug` in my `vimrc` is also not highlighted, which I think should be) I tried with a bare  cpp file also, one that does not use any macros and typedefs, it has the same issue, function name takes a while to get highlighted, but then goes away. I think this might have something to do with coc, since I've noticed colors go away shortly after the suggestions appear, but I don't know for sure. 

![Screenshot from 2021-07-28 17-50-22](https://user-images.githubusercontent.com/30972106/127321845-df035cb5-9fc7-425f-bc10-6310a18c5ece.png)
![Screenshot from 2021-07-28 17-47-17](https://user-images.githubusercontent.com/30972106/127321856-d1471459-b078-43a6-99b8-9df79f165535.png)

- Operating system/version: Ubuntu 21.4
- Terminal emulator/version: alacritty 0.10.0-dev
- `echo $TERM`: xterm-256color
- `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 15 2021 12:29:39)

### Minimal vimrc that can reproduce this bug

```vim
call plug#begin('~/.vim/plugged')

" Nord Color scheme
Plug 'arcticicestudio/nord-vim'
" Sonokai
Plug 'sainnhe/sonokai'
"Status/Tab line
Plug 'vim-airline/vim-airline'
" Themes for status bar
Plug 'vim-airline/vim-airline-themes'
" Tree file explorer
Plug 'preservim/nerdtree'
" Git status for NERDTree
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'
Plug 'preservim/nerdcommenter'
Plug 'plasticboy/vim-markdown'
Plug 'lervag/vimtex'
Plug 'airblade/vim-gitgutter'
" File search, install pulls latest binary
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-fugitive'
Plug 'honza/vim-snippets'
Plug 'neoclide/coc.nvim', { 'branch' : 'release' }

call plug#end()

filetype plugin indent on

""""""" Sonokai """""""
if has('termguicolors')
  set termguicolors
endif
" andromeda, atlantis, shusia, maia, espresso
" let g:sonokai_style = 'espresso'
let g:sonokai_diagnostic_line_highlight = 1
let g:sonokai_better_performance = 1
colorscheme sonokai

```

**Comment by sainnhe** [comment]
I can't reproduce this bug using your vimrc.

But I guess it's caused by semantic highlighting provided by coc, did you enable semantic highlighting in your coc-settings.json?

**Comment by TheCharmingSociopath** [comment]
Okay, this is not a theme issue but related to coc-clangd `semanticToken` implementation, [here is the issue](https://github.com/clangd/coc-clangd/issues/298).
Fairly new to vim and didn't know about semantic highlights, so thought it's a theme issue 😅. Thanks for the response!
