### ISSUE TITLE
How to customise sign column

### ISSUE THREAD

**Issue by kaykhan** [sainnhe/sonokai#32]
Hi,

I am using vim gitgutter, how do i get my sign column took like urs in the screenshot. Where the change is a block color instead if the default `+,~, -`

![image](https://user-images.githubusercontent.com/5202527/130357485-25228a28-730f-4e47-96b4-e2752bab1f1a.png)

![image](https://user-images.githubusercontent.com/5202527/130357516-e4044b02-5e6f-420f-ac59-63dda9b930eb.png)

**Comment by sainnhe** [comment]
Check my config: https://github.com/sainnhe/dotfiles/blob/a26ef2d03b60179a265a2888c323993547d9553f/.config/nvim/coc-settings.json#L74-L78
