### ISSUE TITLE
set hi CocRustChainingHint  guifg=Grey

### ISSUE THREAD

**Issue by audacioustux** [sainnhe/sonokai#33]
set: hi CocRustChainingHint  guifg=Grey
for better readability

https://github.com/fannheyward/coc-rust-analyzer/issues/365#issuecomment-738673943

current:
<img width="1434" alt="Screenshot 2021-09-01 at 3 17 11 PM" src="https://user-images.githubusercontent.com/7238675/131645925-3e8570e7-bf8a-4e32-97b1-93ff7b1d1f46.png">
expected:
<img width="1479" alt="Screenshot 2021-09-01 at 3 16 45 PM" src="https://user-images.githubusercontent.com/7238675/131646026-951e4f4a-fa52-4f9a-b7a8-2cd9677b2cb4.png">

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/sonokai/commit/61b796d94e7b0110f1bdf321cc1d19a841697a42
