### ISSUE TITLE
Parameters are not colored differently (treesitter)

### ISSUE THREAD

**Issue by theteachr** [sainnhe/sonokai#35]
#### Expected

Differently colored parameters
![image](https://user-images.githubusercontent.com/64728420/134138657-0ab17d0e-a7fb-4c57-84f5-8ccd9e0f8fcf.png)

#### Actual

Parameters are the same color as the function name
![image](https://user-images.githubusercontent.com/64728420/134138957-22cdd73c-5ddf-4ca8-8209-cabce5cf4522.png)

**Comment by sainnhe** [comment]
Please follow the issue template to provide detailed information.

**Comment by theteachr** [comment]
- Operating System: macOS Catalina (10.15.7)
- Seen on the following Terminal Emulators:
  - Kitty
  - iTerm2
  - Cool Retro Term
- Seen on the following values of `echo $TERM`:
  - `xterm-kitty`
  - `xterm-256color`
  - `xterm`
-  `nvim --version`:

```
NVIM v0.5.0-dev+1444-gc1120ad0e
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1624680915916.local

Features: +acl +iconv +tui
See ":help feature-compile"

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by sainnhe** [comment]
Closed since this issue doesn't follow the issue template.

I've created 2 new issue templates, you can create a new issue following one of them if you want.
