### ISSUE TITLE
How'd you get your tabs, lightline and tmux panels to look like this?

### ISSUE THREAD

**Issue by fr3fou** [sainnhe/sonokai#4]
I like the litle powerline-like triangles, what font is that / symbol? Mind sharing your .vimrc?

![image](https://user-images.githubusercontent.com/1344906/78605142-af844c80-7863-11ea-92c5-9d5305ff228b.png)

**Comment by sainnhe** [comment]
See [this](https://gist.github.com/sainnhe/b8240bc047313fd6185bb8052df5a8fb)

**Comment by fr3fou** [comment]
thx
