### ISSUE TITLE
Implementation for nvim-lualine/lualine.nvim

### ISSUE THREAD

**Issue by jorgebef** [sainnhe/sonokai#44]
Hello,

I've been happily using sonokai for quite some time and I have recently transitioned as much as possible to lua in my neovim.
Additionally, I have started using lualine as my go-to powerline.
I have been reviewing their documentation and they offer a default template to create a new theme that, if interested, we can implement in this theme.

As per their wiki:
"Note to colorscheme authors : If you want to support lualine. You can put your lualine theme at lua/lualine/themes/{your_colorscheme}.lua in you repo."

I have gone ahead and implemented this for myself and believe it might be positive to include it in this repo as it provides additional support for a now very popular neovim plugin.

If you believe this could be positive, I can create a PR for you to review.

Thank you!

**Comment by sainnhe** [comment]
Of course, thanks!

Let's continue to discuss in #43 .
