### ISSUE TITLE
Highlight GitSignsCurrentLineBlame

### ISSUE THREAD

**Issue by hillaryychan** [sainnhe/sonokai#45]
Hello,

I recently start using [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) and when testing out the blamer found that the font colour was very difficult to read for this colourscheme.
![image](https://user-images.githubusercontent.com/44228565/145997386-27bff480-7343-47d7-af70-39a9ba3274b0.png)

Compared to the highlight set for [blamer.vim](https://github.com/APZelos/blamer.nvim) which is much easier to read.
![image](https://user-images.githubusercontent.com/44228565/145997528-ff039c40-31d0-48f9-8d42-25fc509d285d.png)

After some digging I found that it was because gitsigns declares `NonText` as the highlight group for `GitSignsCurrentLineBlame`. See https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns/highlight.tl#L39

I think there are a few ways we could approach this
1. change `NonText` to a colour more legible to the colourscheme background, or
2. add `GitSignsCurrentLineBlame` as one of the highlight groups for the [gitsigns section](https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim#L856-L861) with same colours as the `Blamer` highlight group

Not sure what you think would be best for this, but I would like it if I could use the blamer in gitsigns without struggling to read.

Thanks!

**Comment by sainnhe** [comment]
Should be fixed via https://github.com/sainnhe/sonokai/commit/8e66ab03cc0bc67d2519a262d1f3f613a36a03ba
