### ISSUE TITLE
spelling errors not coloured anymore

### ISSUE THREAD

**Issue by st-bender** [sainnhe/sonokai#47]
### Operating system/version

Xubuntu

### Terminal emulator/version

xterm

### $TERM environment variable

xterm-256color

### Tmux version

2.1

### Feature matrix

```
❯ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 28 2021 11:23:15)
Included patches: 1-3232
Compiled by conda@717a43540b0d
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sodium            -xfontset
+digraphs          +mouse             -sound             -xim
-dnd               -mouseshape        +spell             -xpm
-ebcdic            +mouse_dec         +startuptime       -xsmp
+emacs_tags        -mouse_gpm         +statusline        -xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/ben/Work/miniconda3/envs/20200805/share/vim"
Compilation: /home/conda/feedstock_root/build_artifacts/vim_1627471090317/_build_env/bin/x86_64-conda-linux-gnu-c
c -c -I. -Iproto -DHAVE_CONFIG_H -DNDEBUG -O2 -isystem /home/ben/Work/miniconda3/envs/20200805/include -I/home/be
n/Work/miniconda3/envs/20200805/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-str
ong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ben/Work/miniconda3/envs/20200805/include -fdebug-prefi
x-map=/home/conda/feedstock_root/build_artifacts/vim_1627471090317/work=/usr/local/src/conda/vim-8.2.3232 -fdebug
-prefix-map=/home/ben/Work/miniconda3/envs/20200805=/usr/local/src/conda-prefix -U_FORTIFY_SOURCE -D_FORTIFY_SOUR
CE=1 
Linking: /home/conda/feedstock_root/build_artifacts/vim_1627471090317/_build_env/bin/x86_64-conda-linux-gnu-cc -W
l,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rp
ath,/home/ben/Work/miniconda3/envs/20200805/lib -Wl,-rpath-link,/home/ben/Work/miniconda3/envs/20200805/lib -L/ho
me/ben/Work/miniconda3/envs/20200805/lib -o vim -lm -ltinfo -ldl -L/home/ben/Work/miniconda3/envs/20200805/lib/py
thon3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lrt -lm
```

### Minimal vimrc that can reproduce this bug.

```vim
scriptencoding utf-8
set encoding=utf-8
set termencoding=utf-8

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'sainnhe/sonokai'
call vundle#end()            " required
filetype plugin indent on    " required
syntax on

set t_Co=256

let g:sonokai_transparent_background = 1
let g:sonokai_style = "andromeda"
colorscheme sonokai
```

### Steps to reproduce this bug using minimal vimrc

1. Lauch vim with `vim -u minimal.vim`
2. Type some English text with spelling errors.
3. Enable spell checking with `:setlocal spell spelllang=en_gb`

### Expected behavior

Coloured spell error highlighting.

### Actual behavior

Just underlined spell check error highlighting without colouring.

Must have changed recently, before they were highlighted in red or blue, for example.

**Comment by sainnhe** [comment]
May caused by https://github.com/sainnhe/sonokai/commit/7560b4d00978a2c1bbca20636c3385e2623533f0#diff-0cabb69af5ffdaae20c452eafd100c64e911701ec9597cfed1b63f1f7c6119a6

Can you checkout earlier commit and get it a try?

**Comment by st-bender** [comment]
Hi, thanks for responding.
After looking into it, my guess would be that 9d8c57c2b0bf57082093bf1b162ac492206d35dd is to blame, as it does not matter if it is in tmux or not.
If it was intentional, could it be made configurable?

**Comment by sainnhe** [comment]
It's intentional, this is what it should be like in gvim:

![Screenshot_20220121_112155](https://user-images.githubusercontent.com/37491630/150460044-be8f9b9e-7162-4bf9-876f-40b39eb38b56.png)

---

> If it was intentional, could it be made configurable?

Check the FAQ section in help doc "How to use custom colors?", follow the guide and link the spell hi groups to whatever you like.

But it's more recommended to use another vim client or terminal emulator that supports colored undercurl/underline instead.

**Comment by st-bender** [comment]
Hi,
There is no explanation or issue linked to the commit, and your idea will break a lot of setups, which is not nice. I find it strange to restrict the use to certain terminals or programs, instead of making it optional or having a fall-back solution in the case that not all features are supported.
At least you could think about having an option or some back-up solution instead of shutting other opinions down.
Thanks.

**Comment by sainnhe** [comment]
Sorry for the impolite response, but it's really hard to satisfy everyone.

Check this PR in my another color scheme: https://github.com/sainnhe/gruvbox-material/pull/92

My opinion is that I'll try to provide best defaults for every highlights, and also provide necessary configuration options, but this still doesn't meet everyone's needs.

For those who need more advanced hacking, they may need to use autocmd to customize some hi groups or directly fork this repository.

**Comment by st-bender** [comment]
You should realize that you are not alone in the world, what seems unreasonable to you might be completely reasonable to others.
Why not keep or introduce such an option here and more people would be happy?
Certainly not everyone, but that's all I have been asking for.

**Comment by sainnhe** [comment]
> You should realize that you are not alone in the world, what seems unreasonable to you might be completely reasonable to others.

I agree, but this is not the reason to add a new config option. A new option should only be added when many people have different ideas about something.

You are the second user to open an issue asking for spelling highlights, so now I think this option is necessary. I'm going to add it later.

**Comment by st-bender** [comment]
We might disagree on that and even if you think that an extra option may not be necessary, be assured that it is very much appreciated.

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/sonokai/commit/807e78ef6a45cc3c2b21f8cf981225ee8e4dc35a
