### ISSUE TITLE
Please add an option to disable terminal color

### ISSUE THREAD

**Issue by nakatuba** [sainnhe/sonokai#49]
Thank you for providing such a nice plugin!

Could you add an option to disable terminal color?

**Comment by sainnhe** [comment]
What do you mean by "disable terminal color"?

Is that the built-in terminal color or the cterm highlight tokens?

**Comment by nakatuba** [comment]
Sorry, I meant the built-in terminal color.
I want to able to optionally disable built-in terminal color settings.

https://github.com/sainnhe/sonokai/blob/a3870fd0c67f2eae4cc1c2db1252d685ee1ea8f3/colors/sonokai.vim#L311-L350

**Comment by sainnhe** [comment]
Sorry, I didn't get the point why we need this option.

If this is only your personal needs, maybe it's better to fork this repository and delete related code by yourself.

**Comment by thatsmydoing** [comment]
When running nvim in a terminal, we'd want the terminal colors (for the prompt, etc) to remain the same when using `:terminal` in nvim and outside of nvim.

As a workaround for nvim, you can also run

```
unlet! g:terminal_color_0
unlet! g:terminal_color_1
unlet! g:terminal_color_2
unlet! g:terminal_color_3
unlet! g:terminal_color_4
unlet! g:terminal_color_5
unlet! g:terminal_color_6
unlet! g:terminal_color_7
unlet! g:terminal_color_8
unlet! g:terminal_color_9
unlet! g:terminal_color_10
unlet! g:terminal_color_11
unlet! g:terminal_color_12
unlet! g:terminal_color_13
unlet! g:terminal_color_14
unlet! g:terminal_color_15
```
after you've loaded the colorscheme. And I assume `unlet! g:terminal_ansi_colors` works the same for vim.

**Comment by sainnhe** [comment]
OK, I got it. Done via https://github.com/sainnhe/sonokai/commit/cf201bf780ca5bf800a6c62869c1cf0395aed9ac

**Comment by thatsmydoing** [comment]
Thank you!
