### ISSUE TITLE
Airline theme doesn't match lightline theme

### ISSUE THREAD

**Issue by dutchgecko** [sainnhe/sonokai#5]
Hi,

I'm using airline, but have some significant colour differences in the statusline compared to your screenshots. Looking at the airline and lightline theme files in this repository I can already see some differences:

| Mode | Airline | Lightline |
| --- | --- | --- |
| Normal | Red | Blue |
| Insert | Blue | Green |
| Visual | Purple | Purple |
| Replace | Green | Yellow |

Tab colours are the same.

From the screenshots, I much prefer the Lightline colour choices, so I would be grateful if the Airline theme could be updated to match.

edit: additionally, no highlighting has been set for the sections `airline_section_error` and `airline_section_warning`, these are displayed in the default red and yellow.

**Comment by sainnhe** [comment]
Should be fixed via af23432.

**Comment by dutchgecko** [comment]
Seems to work great! Thanks for the quick fix.

**Comment by dutchgecko** [comment]
Hi, I've noticed a tiny issue with this fix. When a buffer is marked modified, the warning and error sections revert to their default colours.

**Comment by sainnhe** [comment]
Fixed.

**Comment by dutchgecko** [comment]
Perfect, thanks again!
