### ISSUE TITLE
Jetbrains Port

### ISSUE THREAD

**Issue by padermon** [sainnhe/sonokai#51]
The colorscheme is awesome. Are there any plans for JetBrains IDEs?

**Comment by wrestlerdude** [comment]
Yup, agreed. It would be brilliant to have this

**Comment by antoineco** [comment]
I'd love to see that happen and contributions are always welcome! Feel free to add them to https://github.com/sainnhe/sonokai/wiki/Related-Projects

Closing because not directly related to the Vim color scheme.
