### ISSUE TITLE
How to install with Plug?

### ISSUE THREAD

**Issue by 0xdeface** [sainnhe/sonokai#52]
Hello. Can i install this colorscheme by Plug ?

**Comment by sainnhe** [comment]
It's documented.

https://github.com/sainnhe/sonokai/blob/774ccdb95a04539530be34fa17a34c0f64139aca/doc/sonokai.txt#L52-L63

**Comment by 0xdeface** [comment]
Sorry, yesterday night at 1:00, Plug can install but colorcheme dont aplly (not found), apparently i sealed up. now it all work
