### ISSUE TITLE
eval palette->extend(a:colors_override) cause E492: not an editor command.

### ISSUE THREAD

**Issue by qicai21** [sainnhe/sonokai#60]
### Operating system/version

ubuntu 20.04

### Terminal emulator/version

neovim

### $TERM environment variable

echoxterm-256color

### Feature matrix

health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#translator#check
========================================================================
  - OK: Async check passed
  - OK: Floating window check passed
  - OK: Using python3

health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.4.3
  - INFO: Node version: v14.19.3

  - INFO: Script: /home/qicai21/.local/share/nvim/plugins/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/qicai21/anaconda3/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /home/qicai21/anaconda3/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.12
  - INFO: pynvim version: 0.4.2 (outdated; from ~/anaconda3/lib/python3.8/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.19.3
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

### Minimal vimrc that can reproduce this bug.

```sonokai/autoload/sonokai.vim
" row 187
eval palette->extend(a:colors_override)
  return palette
endfunction "}}}
 ```

### Steps to reproduce this bug using minimal vimrc

launch neovim with nvim command, and showing E492

### Expected behavior

ditto

### Actual behavior

ditto

**Comment by sainnhe** [comment]
Should be fixed now.

**Comment by ljmf00** [comment]
@sainnhe Can you do a new release?
