### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ljmf00** [sainnhe/sonokai#61]
Sorry, it was somewhat related to https://github.com/sainnhe/sonokai/issues/60.

I made this dependency a pinned commit rather than a pinned tag since I wanted some features/fixes from it. Because I recently updated it and got into some issues, and, the latest release was a bit old I decided to bring this up.

Is it possible to have a new release or do you have a specific release schedule?

**Comment by sainnhe** [comment]
> Is it possible to have a new release or do you have a specific release schedule?

I plan to add a new option that can customize the color palette, and also some plugins need to be optimized, then I'll create a new release.

Btw, why not use a plugin manager to get the latest revision?
