### ISSUE TITLE
Better ruby highlights

### ISSUE THREAD

**Issue by gabrielsugai** [sainnhe/sonokai#62]
Hi guys, it's not a bug, but, is there a way to get a better ruby highlights?
symbols, and some functions, hash keys dont get highlighted 😔 and i realy liked this colorscheme 😅

<img width="505" alt="image" src="https://user-images.githubusercontent.com/26432843/170738344-7e2bbd34-7bd7-475d-9122-2ee7201184fc.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/26432843/170738845-b552dc14-1fcc-4c1e-bcea-10e708e2e394.png">

**Comment by sainnhe** [comment]
The default highlight engine is too bad that many tokens can't be colored.

Try semantic highlight engine (in coc.nvim) or nvim-treesitter.

This is what it looks like when using tree-sitter.

![截屏2022-05-28 下午5 05 12](https://user-images.githubusercontent.com/37491630/170818768-28aa0990-e28b-475d-8ca3-09512f6b5c19.png)

**Comment by gabrielsugai** [comment]
> The default highlight engine is too bad that many tokens can't be colored.
> 
> Try semantic highlight engine (in coc.nvim) or nvim-treesitter.
> 
> This is what it looks like when using tree-sitter.
> 
> ![截屏2022-05-28 下午5 05 12](https://user-images.githubusercontent.com/37491630/170818768-28aa0990-e28b-475d-8ca3-09512f6b5c19.png)

Thanks for the help,
But im a little newbie at this haha, i tried to found how i configure semantic highlight at `coc-settings.json`, but i failed 😔🥲
could you show how can i do that?

**Comment by sainnhe** [comment]
Some language servers don't support semantic highlighting feature. If you are using https://solargraph.org/guides/language-server , this feature is not supported.

I'd suggest tree-sitter instead, it's more general in use of most languages, and has better highlighting most of the time.

**Comment by gabrielsugai** [comment]
Oh thanks its perfect now haha it works with tree-sitter, thank u 😎
