### ISSUE TITLE
Add WinBar and WinBarNC

### ISSUE THREAD

**Issue by registerGen** [sainnhe/sonokai#64]
Thank you for the colorscheme!

ref: neovim/neovim#18562

**Comment by sainnhe** [comment]
The default highlight of `WinBar` is

```
:hi WinBar
WinBar         xxx cterm=bold gui=bold
```

IMO it is reasonable enough, but `WinBarNC` is linked to `WinBar` so it's also white bold.

```
:hi WinBarNC
WinBarNC       xxx links to WinBar
```

Maybe changing it to grey will be better?

Could you try this:

```vim
:hi! link WinBarNC Grey
```

**Comment by registerGen** [comment]
Yep. That does make sense!

**Comment by registerGen** [comment]
Maybe a lighter background is better?

Here's my config:

```lua
vim.fn['sonokai#highlight']('WinBar', palette.fg, palette.bg3, 'bold')
vim.fn['sonokai#highlight']('WinBarNC', palette.grey, palette.bg3, 'bold')
```

**Comment by sainnhe** [comment]
IMO that will make the winbar more like a status line. I set laststatus=3 to avoid this, so I think using normal bg should be better.

**Comment by registerGen** [comment]
Well I think this should depend on what users want to do (for example, I use winbar to display the symbol path). You can just use normal bg as default and let users configure them.

**Comment by sainnhe** [comment]
Sorry for late reply, I'm so busy recently.

For small UI modification like this, adding a configuration option might be overkill. Users ought to use custom colors in their vimrc.

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/sonokai/commit/93d6f268f65b8208a46e725da7e0cd759cc7b297

**Comment by registerGen** [comment]
Thanks!
