### ISSUE TITLE
Error when define colorscheme sonokai

### ISSUE THREAD

**Issue by Danielwsx64** [sainnhe/sonokai#71]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

Ubuntu 22.04.1 LTS

### Terminal emulator/version

Version 3.44.0 for GNOME 42

### $TERM environment variable

screen-256color

### Tmux version

tmux 3.2a

### Feature matrix

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6800'
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: unsupported version `cargo 1.59.0 (49d8809dc 2022-02-10)`. Some cargo installations require Rust >= 1.60.0.
  - OK: **luarocks**: `/home/daniel/.asdf/installs/lua/5.4.4/luarocks/bin/luarocks 3.9.0`
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.3.1`
  - OK: **node**: `v16.14.0`
  - OK: **python3**: `Python 3.10.4`
  - OK: **pip3**: `pip 22.0.4 from /home/daniel/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 11.0.16`
  - OK: **java**: `openjdk version "11.0.16" 2022-07-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: qui 08 set 2022 14:50:53.

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /home/daniel/.asdf/shims/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.14.0
  - WARNING: Missing "neovim" npm (or yarn, pnpm) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - Run in shell (if you use pnpm): pnpm install -g neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## Telescope Extension: `ag`
  - INFO: No healthcheck provided

## Telescope Extension: `danielws`
  - INFO: No healthcheck provided

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `gh`
  - INFO: No healthcheck provided

## Telescope Extension: `luasnip`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

## Telescope Extension: `project`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/daniel/.local/state/nvim/lsp.log
  - INFO: Log size: 5701 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>(comment_toggle_linewise)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Plug>(comment_toggle_blockwise)`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>"**
  - INFO: old rhs: `<Nop>`
  - INFO: new rhs: `<cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"x"**, buf: 0, lhs: **"<leader>"**
  - INFO: old rhs: `<Nop>`
  - INFO: new rhs: `<cmd>lua require("which-key").show(" ", {mode = "v", auto = true})<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>zs"**
  - INFO: old rhs: `<cmd>PackerSync<CR>`
  - INFO: new rhs: `<CMD>PackerSync<CR>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>ff"**
  - INFO: old rhs: `<cmd>Telescope find_files<cr>`
  - INFO: new rhs: `<CMD>Telescope find_files<CR>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>ce"**
  - INFO: old rhs: `:e $MYVIMRC <CR>`
  - INFO: new rhs: `<CMD>e $MYVIMRC<CR>`

### Minimal vimrc that can reproduce this bug.

		-- My config using packer
		use({ "sainnhe/sonokai", config = function ()
			
			vim.g.sonokai_better_performance = 1
			vim.g.sonokai_style = "default"

			vim.cmd("colorscheme sonokai")
		end })

### Steps to reproduce this bug using minimal vimrc

Just open nvim

### Expected behavior

Load nvim with sonokai colorscheme

### Actual behavior

An error when try read `sonokai/colors/sonokai.vim`
```
Error detected while processing /home/daniel/.local/share/nvim/site/pack/packer/start/sonokai/colors/sonokai.vim:
line  425:
W18: Invalid character in group name
line  426:
W18: Invalid character in group name
line  427:
W18: Invalid character in group name
line  428:
W18: Invalid character in group name
line  429:
W18: Invalid character in group name
line  430:
W18: Invalid character in group name
line  431:
W18: Invalid character in group name
line  432:
W18: Invalid character in group name
line  433:
W18: Invalid character in group name
line  434:
W18: Invalid character in group name
line  435:

**Comment by antoineco** [comment]
@Danielwsx64 please update to Neovim's latest nightly. You are using a development version of Neovim (`0.8.0-dev`), and the Treesitter highlight groups have been completely reworked recently.
