### ISSUE TITLE
How to change style to Andromeda in lua?

### ISSUE THREAD

**Issue by Sudeep-Sharma0-0** [sainnhe/sonokai#76]
I installed this in neovim and can't figure out how to change style to andromeda from default one.

**Comment by Sudeep-Sharma0-0** [comment]
Ok I don't know why I never thought of this but its just:

`vim.cmd ("let g:sonokai_style = 'andromeda'")`

**Comment by antoineco** [comment]
@Sudeep-Sharma0-0 it's even simpler than that:

```lua
vim.g.sonokai_style = 'andromeda'
```
