### ISSUE TITLE
Emacs Port?

### ISSUE THREAD

**Issue by xmawja** [sainnhe/sonokai#77]
The colorscheme is awesome. Are there any plans for Emacs IDEs?

**Comment by sainnhe** [comment]
No I don't use emacs.

**Comment by xmawja** [comment]
> No I don't use emacs.

**so can i port it ?** to be the default on  [FUNMACS](https://github.com/xmawja/funmacs.git) **:)**

**Comment by sainnhe** [comment]
Yes, absolutely ;)

**Comment by xmawja** [comment]
**Thx**  **;)**
