### ISSUE TITLE
bufferline

### ISSUE THREAD

**Issue by kaykhan** [sainnhe/sonokai#78]
any support planned for a bufferline theme integration? https://github.com/akinsho/bufferline.nvim

**Comment by sainnhe** [comment]
It doesn't provide plugin specific highlight groups, so looks like this plugin can't be optimized at color scheme level.

https://github.com/akinsho/bufferline.nvim/blob/4ecfa81e470a589e74adcde3d5bb1727dd407363/doc/bufferline.txt#L709

**Comment by antoineco** [comment]
As far as I can tell, bufferline.nvim doesn't look all that bad with this coloscheme. All colors are [derived from core highlight groups](https://github.com/akinsho/bufferline.nvim/blob/v3.7.0/lua/bufferline/config.lua#L278-L293) (with shading automatically applied), and therefore should already match the colorscheme.

Any specific concern?

![image](https://user-images.githubusercontent.com/3299086/233810938-f125dd11-8ec4-4125-b178-8c7c245fec68.png)

Ref. https://github.com/sainnhe/everforest/issues/121 for a known issue with LSP diagnostic colors.

**Comment by kaykhan** [comment]
Hmm i cna't remember what this was in relation to, so this can be closed
