### ISSUE TITLE
Can't have transparent background Everywhere 

### ISSUE THREAD

**Issue by RichestHumanAlive** [sainnhe/sonokai#79]
>Edit : I finally found that I just had to define the following highlight commands:
```lua
vim.cmd("hi NormalFloat ctermbg=NONE guibg=NONE")
vim.cmd("hi FloatTitle ctermbg=NONE guibg=NONE")
vim.cmd("hi FloatBorder ctermbg=NONE guibg=NONE")
```

And here is the result for `Mason.nvim` for example :

Went from :
![image](https://user-images.githubusercontent.com/47452191/209038482-4821e1c4-336f-48fe-96b3-52f21cde8d93.png)

to:
![image](https://user-images.githubusercontent.com/47452191/209597671-d99f23e3-4883-4ffa-b8cb-85d67c96fabf.png)

---

### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

Windows 11 Pro Insider Preview 22H2 - OS build 25252.1000

### Terminal emulator/version

Powershell 7.3.0-rc.1

### $TERM environment variable

NULL

### Feature matrix

diffview: require("diffview.health").check()
========================================================================
## Checking plugin dependencies
  - OK: plenary installed.
  - OK: nvim-web-devicons installed.

## Checking external dependencies
  - OK: Git found.
  - OK: Git is up-to-date.

gitsigns: require("gitsigns.health").check()
========================================================================
  - OK: git version 2.37.0.windows.1

lsp: health#lsp#check
========================================================================
## server status
  - OK: omnisharp-lsp: running

## server configuration: omnisharp-lsp
  - INFO: 	
    ### allowlist
    ['cs']

## Performance
  - OK: Using lua for faster performance.

mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - OK: **Composer**: `Composer version 2.3.7 2022-06-06 16:43:28
`
  - OK: **PHP**: `PHP 8.0.14 (cli) (built: Dec 16 2021 10:25:26) ( ZTS Visual C++ 2019 x64 )`
  - OK: **npm**: `9.1.2`
  - OK: **node**: `v16.15.1
`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **javac**: `javac 11.0.12
`
  - OK: **java**: `openjdk version "11.0.12" 2021-07-20
`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.85.0 (Windows) libcurl/7.85.0 Schannel
`
  - WARNING: **gzip**: not available
  - OK: **tar**: `bsdtar 3.6.1 - libarchive 3.6.1 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - ERROR: **pwsh**: not available
  - OK: **python**: `Python 3.11.0
`
  - OK: **pip**: `pip 22.3.1 from ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)

`
  - WARNING: **7z**: not available
  - OK: **python3_host_prog**: `Python 3.11.0
`
  - OK: **python3_host_prog pip**: `pip 22.3.1 from ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)

`
  - OK: **JAVA_HOME**: `openjdk version "17.0.3" 2022-04-19
`
  - OK: GitHub API rate limit. Used: 4. Remaining: 56. Limit: 60. Reset: 12/22/2022 3:32:26 AM.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: info: Usage: zig [command] [options]
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.25252",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features         H L F I J
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - zig                 ✓ . ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - help                ✓ . . . ✓
  - comment             ✓ . . . .
  - c_sharp             ✓ ✓ ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - hlsl                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - markdown_inline     ✓ . . . ✓
  - phpdoc              ✓ . . . .
  - todotxt             ✓ . . . .
  - wgsl                ✓ . ✓ ✓ .
  - java                ✓ ✓ . ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - cmake               x . x . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - gitattributes       ✓ . . . ✓
  - gitignore           ✓ . . . .
  - bash                ✓ ✓ ✓ . ✓
  - dockerfile          ✓ . . . ✓
  - dot                 ✓ . . . ✓
  - scss                ✓ . . ✓ .
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: cmake(highlights): ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 824 for language cmake
    cmake(highlights) is concatenated from the following files:
    | [ERROR]:"~\AppData\Local\nvim-data\plugged\nvim-treesitter\queries\cmake\highlights.scm", failed to load: ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 824 for language cmake
  - ERROR: cmake(folds): ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 79 for language cmake
    cmake(folds) is concatenated from the following files:
    | [ERROR]:"~\AppData\Local\nvim-data\plugged\nvim-treesitter\queries\cmake\folds.scm", failed to load: ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 79 for language cmake

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 3 provider (optional)
  - INFO: pyenv: Path: ~\.pyenv\pyenv-win\bin\pyenv.BAT
  - INFO: pyenv: Root: ~\.pyenv\pyenv-win\
  - INFO: Using: g:python3_host_prog = "~\AppData\Local\Programs\Python\Python311\python.exe"
  - INFO: Executable: ~\AppData\Local\Programs\Python\Python311\python.exe
  - INFO: Python version: 3.11.0
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.15.1
  - INFO: Nvim node.js host: ~\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: No usable perl executable found

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.5.3

## Telescope Extension: `projections`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: ~\AppData\Local\nvim-data\lsp.log
  - INFO: Log size: 687 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for diff: ABI version 14
  - OK: Loaded parser for dockerfile: ABI version 14
  - OK: Loaded parser for dot: ABI version 13
  - OK: Loaded parser for gitattributes: ABI version 14
  - OK: Loaded parser for gitignore: ABI version 14
  - OK: Loaded parser for git_rebase: ABI version 14
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for hlsl: ABI version 14
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for http: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for markdown_inline: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for phpdoc: ABI version 14
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for sql: ABI version 14
  - OK: Loaded parser for todotxt: ABI version 13
  - OK: Loaded parser for tsx: ABI version 14
  - OK: Loaded parser for typescript: ABI version 14
  - OK: Loaded parser for vim: ABI version 14
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for wgsl: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for zig: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

### Minimal vimrc that can reproduce this bug.

```vim
call Plug#begin()
	Plug 'sainnhe/sonokai'
call plug#end()

let g:sonokai_style = 'atlantis'
let g:sonokai_better_performance = 1
let g:sonokai_show_eob = 1 
let g:sonokai_diagnostic_text_highlight = 0
let g:sonokai_diagnostic_line_highlight = 0
let g:sonokai_diagnostic_virtual_text = 'grey' 
set background=dark
let g:sonokai_transparent_background=2
colorscheme sonokai
```

### Steps to reproduce this bug using minimal vimrc

1. Launch nvim

2. Show  Lsp Diagnostic popup using 

```vim
:lua vim.lsp.diagnostic.show_line_diagnostics()
```

output:
![image](https://user-images.githubusercontent.com/47452191/209038383-9adf23e6-7398-49ee-a59b-aa1f462b36c9.png)

3. Run command

 ```vim
:LspInfo
```
output: 
![image](https://user-images.githubusercontent.com/47452191/209038308-7ef3adf5-1d07-4ae4-b5d3-faf6cfc80413.png)

4. Run command
```
:Mason
```

output:
![image](https://user-images.githubusercontent.com/47452191/209038482-4821e1c4-336f-48fe-96b3-52f21cde8d93.png)

### Expected behavior

I was expecting transparent backgrounds for for lsp diagnostics popup, `lspinfo` window and `Mason`  window as for the main windows.

For example, something like this for lsp diagnostics: 

![image](https://user-images.githubusercontent.com/47452191/209038836-a12aba76-c8b3-42a3-a6a7-a7f66578205b.png)

### Actual behavior

Opaque background.

 ---

>I am pretty new to the vim ecosystem and maybe the solution to my issue is somewhere else but please be lenient and let me know. 

**Sonokai is an Awesome 💯** !

**Comment by sainnhe** [comment]
I thought setting `NormalFloat` (which is the default highlight group of floating window) to be transparent, but the problem is that not all floating window have a border, instead the designs in most of them are using a brighter background to distinguish between normal background colors, so I gave up this idea.

Another thing that needs to be considered is that vim actually shouldn't make everything transparent, some elements should use a different background color (e.g. the status line). If you want to make your vim fully transparent, you should consider switching to a terminal emulator that supports blurred background (e.g. konsole). This will fully blur every elements in vim, which will look much better.

**Comment by RichestHumanAlive** [comment]
Thank you for your answer and tips 🙂. I understand a little better how the Vim UI works.

Indeed, I use Windows Terminal which supports blurred background and that's why, for better appearance, I disabled as many backgrounds as possible using:

```
let g:sonokai_transparent_background=2
```

Also, what I like about the transparency of Vim is that it is pseudo-transparent actually, inside the Vim UI and you can't see through a floating window even if it's "transparent". 
Floating transparent windows actually just takes the lowest background of the UI at that specific area. 
With borders it's even better like here:

![](https://user-images.githubusercontent.com/47452191/209038836-a12aba76-c8b3-42a3-a6a7-a7f66578205b.png)

Even if there is text behind the floating window, the text will not appear and will be covered by pseudo-transparent background. 
Unless I misunderstood something.

This is precisely want I need to achieve for all my floating windows.

Should look at how to customize the background for each plugin that uses floating windows or is there a way to overwrite the default appearance of all floating windows of Vim?

Thanks in advance for your time 🙂.

**Comment by dmytrodubinin** [comment]
Any solutions for Linux? I have the same problem on Arch Linux with Alacritty. The solution above didn't help.
