### ISSUE TITLE
Any chance of porting the Ristretto filter?

### ISSUE THREAD

**Issue by danilofreire** [sainnhe/sonokai#8]
Hi! Thanks very much for sharing this theme! It's become my absolute favourite! I would just like to kindly ask if you intend to port the Ristretto colour scheme to the current theme. I understand it's a lot of work and you may not like the filter, so I'm sorry if I'm asking too much :) Many thanks again!

**Comment by sainnhe** [comment]
Sorry but I'm not interested in adding it.

But I'd like to point out that adding a custom palette is very easy, you can fork this repo and add it by yourself. Take a look at `colors/sonokai.vim`.

**Comment by ghifarit53** [comment]
I forked this repo and created a Monokai Ristretto filter named 'espresso' on my repo. Check it out [here](https://github.com/ghifarit53/sonokai)
![sonokai-espresso](https://user-images.githubusercontent.com/59758342/84651325-ee094800-af33-11ea-8fcf-300de4f2b674.png)

**Comment by danilofreire** [comment]
Thanks, @ghifarit53! The filter looks great!

**Comment by sainnhe** [comment]
Hello, I just port the Ristretto variant to sonokai, you can update this color scheme and get it a try.

**Comment by danilofreire** [comment]
Many thanks, @sainnhe! That's very kind of you! I'll give it a try right now!
