### ISSUE TITLE
Support Neo-tree.nvim

### ISSUE THREAD

**Issue by kaykhan** [sainnhe/sonokai#88]
I see sonokai has support for nvim-tree. Ive recently migrated from nvim-tree to neo-tree.

Would it be possible to add support for this?
https://github.com/nvim-neo-tree/neo-tree.nvim

In the meantime ive been using this - https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Visual-Customizations#colour-scheme

**Comment by antoineco** [comment]
It looks simple enough 👍  We would do exactly the same as they suggest: link both groups.

**Comment by antoineco** [comment]
I just noticed that we already have a few highlight groups for Neo-tree, so if they don't work, it means that they are probably outdated:

https://github.com/sainnhe/sonokai/blob/c995ad5d01712fdd9c7e9529edb035bd5a2c0b0b/colors/sonokai.vim#L1446-L1466

**Comment by antoineco** [comment]
That is very likely. We did not link this highlight group explicitly, so if both Neo-tree and nvim-tree pick different values, they will look different in both plugins.

Any other difference you think we should address?

**Comment by kaykhan** [comment]
> That is very likely. We did not link this highlight group explicitly, so if both Neo-tree and nvim-tree pick different values, they will look different in both plugins.
> 
> Any other difference you think we should address?

Not that i can think of
