### ISSUE TITLE
help with folke/noice.nvim and mini view

### ISSUE THREAD

**Issue by kaykhan** [sainnhe/sonokai#89]
I recently installed the following plugin https://github.com/folke/noice.nvim which uses `mini` for its notification messages https://github.com/folke/noice.nvim#-views

A small problem im seeing, does anyone know what is causing the background of `eslint` to be a different shade of color to the rest of the line. 

![image](https://user-images.githubusercontent.com/5202527/233831085-fa60c7dc-ec3d-4b8c-9a0c-eafe2f089818.png)

**Comment by antoineco** [comment]
For those of us who neither use noice.nvim nor eslint, could you please provide a reproduction scenario?

- sample typescript file
- sample eslint config and how to configure the LSP server
- steps to reproduce while using noice.nvim

Thank you.

**Comment by antoineco** [comment]
Ref. this request to support noice.nvim: https://github.com/sainnhe/gruvbox-material/issues/148

**Comment by kaykhan** [comment]
Okay i just assume it is not specific to eslint or a particular lsp server. But anyway will try to provide more shortly.

**Comment by antoineco** [comment]
If it can be reproduced without null-ls that's even easier.

**Comment by kaykhan** [comment]
Doing some more digging and found a issue that resembles the problem - https://github.com/folke/noice.nvim/issues/226#issuecomment-1315913597

I managed to resolve it by setting on the noice plugin

```
	views = {
		mini = {
			win_options = {
				winblend = 100,
			},
		},
	},
```
