### ISSUE TITLE
Configuration for dim float window style

### ISSUE THREAD

**Issue by ten3roberts** [sainnhe/sonokai#90]
Floating windows need to stand out, and this is currently done by making them lighter than `Normal`

It would be useful with a configuration variable that makes the floating windows and borders darker.

This would make the highlighting consistent with NvimTree etc.

I prefer this style of having "util" or non-text windows darker.

Something along the lines of 

```vim
g:sonokai_float_style=dim/bright
```

**Comment by antoineco** [comment]
@ten3roberts dark floating windows is a popular style indeed. The current style pre-dates the addition of `bg_dim` to the palette (78daf8e71cb0c83abaf9f7863dfcec7c2bd6baf3), but now a "dark" float style should be totally achievable.

Would you mind trying this autocmd (assuming Neovim) and report on potential inconsistencies? (especially if you use fancy borders around floating windows). I'll do the same on my side.

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
  group = vim.api.nvim_create_augroup("custom_highlights_sonokai", {}),
  pattern = "sonokai",
  callback = function()
    local config = vim.fn["sonokai#get_configuration"]()
    local palette = vim.fn["sonokai#get_palette"](config.style, config.colors_override)
    local set_hl = vim.fn["sonokai#highlight"]

    set_hl("NormalFloat", palette.fg, palette.bg_dim)
  end
})
```

before

![image](https://github.com/sainnhe/sonokai/assets/3299086/0d117c9b-3748-4e1a-a250-261aa2bab90a)
![image](https://github.com/sainnhe/sonokai/assets/3299086/8451691a-30f1-4929-84fa-114c52c93015)

after

![image](https://github.com/sainnhe/sonokai/assets/3299086/ec852d6a-0d37-4430-b489-89ac7198fdf6)
![image](https://github.com/sainnhe/sonokai/assets/3299086/6644b60a-0cf6-4124-b58b-14acdfd9545e)
