### ISSUE TITLE
Add support for NotifyBackground

### ISSUE THREAD

**Issue by matadaniel** [sainnhe/sonokai#96]
Thank you for the effort you've put into this awesome color scheme!

I'm using the following options and get the following warning. 

sonokai_style = "maia"                   
sonokai_enable_italic = 1                
sonokai_transparent_background = 2       
sonokai_current_word = "grey background" 

![2024-02-15T18:23:00,296585435-06:00](https://github.com/sainnhe/sonokai/assets/100956688/64bccf93-e23f-4588-a6d0-4b55178a9efe)

**Comment by antoineco** [comment]
Good catch 👍 

I haven't been using nvim-notify but it seems like we need to set a few more groups:

https://github.com/rcarriga/nvim-notify/blob/7138c86b28de61b6866c8cae60289136f0d539fa/lua/notify/config/highlights.lua#L5-L28
