### ISSUE TITLE
Would you be interested in a PR for a new palette?

### ISSUE THREAD

**Issue by llimllib** [sainnhe/sonokai#97]
Hi! I love sonokai, and I've been using it with a custom palette for a long while now. My palette is based on green, brown, and blue:

<img width="1044" alt="image" src="https://github.com/sainnhe/sonokai/assets/7150/936abdcb-e087-4d00-bd97-223253760cb1">

Here's the palette with colors; it doesn't have as many different colors as the base schemes do:

<img width="298" alt="image" src="https://github.com/sainnhe/sonokai/assets/7150/28f7e522-dce9-4b72-be79-d076e3d1f6d6">

I could work it up as a PR if you're interested, otherwise no worries.

<details><summary>The palette table</summary>

```
vim.g.sonokai_colors_override = {
	black = { "#181a1c", "232" },
	bg_dim = { "#24272e", "232" },
	bg0 = { "#252A39", "235" },
	bg1 = { "#2a3041", "236" },
	bg2 = { "#2f3548", "236" },
	bg3 = { "#343b50", "237" },
	bg4 = { "#394158", "237" },
	bg_red = { "#ff6d7e", "203" },
	diff_red = { "#55393d", "52" },
	bg_green = { "#a5e179", "107" },
	diff_green = { "#394634", "22" },
	bg_blue = { "#7ad5f1", "110" },
	diff_blue = { "#354157", "17" },
	diff_yellow = { "#4e432f", "54" },
	fg = { "#e1e3e4", "250" },
	red = { "#F47648", "203" },
	orange = { "#8ED0B2", "215" },
	yellow = { "#8ED0B2", "179" },
	green = { "#40BA93", "107" },
	blue = { "#73D0FF", "110" },
	purple = { "#fca07f", "176" },
	grey = { "#828a9a", "246" },
	grey_dim = { "#5a6477", "240" },
	none = { "NONE", "NONE" },
}
```

</details>

**Comment by sainnhe** [comment]
Sorry but the palettes in this repo has been stabilized and should not be changed in the future. Maybe you should maintain your own color scheme repository instead.

**Comment by llimllib** [comment]
np! I actually had it in my own repo and closed it because it felt dumb to maintain a whole repo just for the one table.

Figured that was the case, but just thought I'd ask.

**Comment by antoineco** [comment]
It's not dumb, your colorscheme is cool :)

The are a lot of colorschemes out there which were born from existing palettes/codebases. If you want to maintain your own, go ahead and find a great name for it. We can obviously not multiply built-in palettes indefinitely in this repo, but we endorse creativity and customization in people who enjoy to create derivative work out it.

**Comment by llimllib** [comment]
>  If you want to maintain your own

Yeah that was the pain point, I like my custom color table but I have no desire to try and keep up with all the new treesitter stuff, or even to remember to rebase off your upstream code.

Leaving it here and on my archived repo is plenty enough for me. Thanks!
