### ISSUE TITLE
Is there a way to toggle the transparency setting at runtime?

### ISSUE THREAD

**Issue by svanharmelen** [sainnhe/sonokai#98]
I would like to toggle transparency using FocusGained and FocusLost autocmds, but it looks like updating the global var doesn't change anything after the config is inittially loaded.

Would this, somehow, be possible? Thanks!

**Comment by antoineco** [comment]
Indeed changing the variable alone won't have any effect, you also have to reload the colorscheme by calling `colorscheme sonokai` after setting the variable.

Alternatively, since transparency doesn't affect that many highlight groups (~15), it should be possible to avoid the full reload by simply (re-)setting those highlight groups inside your autocmds ([example](https://github.com/sainnhe/sonokai/blob/da162343354fbd9bf9cd49293a856f0e3761e8ac/doc/sonokai.txt#L555-L560)).
Given how fast Vim can load a colorscheme, I am not convinced that it is worth the trouble though.

Let me know if you need a code sample, I'm happy to assist.

**Comment by svanharmelen** [comment]
Thanks for the response! Will try this tomorrow, but I guess this (easy) fix will do just fine 😊

**Comment by svanharmelen** [comment]
It doesn't quite work as expected. I now have this in my nvim config:

```lua
-- Make background solid again
autocmd('FocusGained', {
  callback = function()
    vim.g.sonokai_transparent_background = 0
    vim.cmd [[ colorscheme sonokai ]]
    vim.cmd [[ echom 'gained']]
  end
})

-- Make background transparent
autocmd('FocusLost', {
  callback = function()
    vim.g.sonokai_transparent_background = 2
    vim.cmd [[ colorscheme sonokai ]]
    vim.cmd [[ echom 'lost']]
  end
})
```

When switching to another tmux pane it does make the background transparent and shows the "lost" message. But when switching back to the nvim pane it doesn't change the background back again. It does show the "gained" message so the autocmd is triggered correctly.

Any ideas on how to "fix" it? Thanks!

**Comment by svanharmelen** [comment]
Hmm... Hold on... It looks like it does work, but it doesn't restore all the components 😏 I do have a custom func like this, would that play a role in this?

```lua
return {
  'sainnhe/sonokai',
  priority = 1000,

  config = function()
    -- Define locals
    local autocmd                           = vim.api.nvim_create_autocmd
    local cmd                               = vim.cmd
    local fn                                = vim.fn
    local hl                                = vim.api.nvim_set_hl
    local set                               = vim.opt

    -- Configure Sonokai
    vim.g.sonokai_better_performance        = 1
    vim.g.sonokai_diagnostic_line_highlight = 1
    vim.g.sonokai_disable_italic_comment    = 1
    vim.g.sonokai_enable_italic             = 1

    -- Set terminal GUI colors
    if fn.has('termguicolors') == 1 then
      set.termguicolors = true
    end

    -- Create custom config function
    local function sonokaiCustom()
      hl(0, 'CopilotSuggestion', { link = 'Comment' })
      hl(0, 'DiagnosticVirtualTextError', { link = 'DiagnosticSignError' })
      hl(0, 'DiagnosticVirtualTextHint', { link = 'DiagnosticSignHint' })
      hl(0, 'DiagnosticVirtualTextInfo', { link = 'DiagnosticSignInfo' })
      hl(0, 'DiagnosticVirtualTextWarn', { link = 'DiagnosticSignWarn' })
      hl(0, 'NvimTreeDiagnosticErrorIcon', { link = 'DiagnosticSignError' })
      hl(0, 'NvimTreeDiagnosticHintIcon', { link = 'DiagnosticSignHint' })
      hl(0, 'NvimTreeDiagnosticInfoIcon', { link = 'DiagnosticSignInfo' })
      hl(0, 'NvimTreeDiagnosticWarnIcon', { link = 'DiagnosticSignWarn' })
      hl(0, 'TelescopeResultsDiffAdd', { link = 'GreenSign' })
      hl(0, 'TelescopeResultsDiffChange', { link = 'YellowSign' })
      hl(0, 'TelescopeResultsDiffDelete', { link = 'RedSign' })
      hl(0, 'TelescopeResultsDiffUntracked', { link = 'Comment' })
      hl(0, 'WindowPickerStatusLine', { link = 'NvimTreeWindowPicker' })
      hl(0, 'WindowPickerStatusLineNC', { link = 'NvimTreeWindowPicker' })

      local palette = fn.eval("sonokai#get_palette('default', {})")
      fn['sonokai#highlight']('CursorLine', palette.none, palette.bg2)
      fn['sonokai#highlight']('CursorLineNr', palette.fg, palette.bg4)
      fn['sonokai#highlight']('LineNr', palette.grey, palette.bg1)
      fn['sonokai#highlight']('Search', palette.bg0, palette.yellow)
      fn['sonokai#highlight']('IncSearch', palette.bg0, palette.bg_green)
      fn['sonokai#highlight']('VertSplit', palette.grey, palette.none)
    end

    -- Create an autocommand to call the custom config function
    autocmd('ColorScheme', {
      pattern = 'sonokai',
      callback = sonokaiCustom
    })

    -- Set the colorscheme
    cmd [[colorscheme sonokai]]
  end,
}
```

**Comment by antoineco** [comment]
I tried to reproduce and was able to confirm that the function `sonokaiCustom()` (inside the `config` callback) is only being called on the _first_ call to `colorscheme sonokai`.

(Neo)vim seems to ignore `ColorScheme` autocmds when the pattern matches the colorscheme that's already loaded. However, I was able to make it work with a wildcard colorscheme pattern instead:

```lua
function sonokaiCustom()
  if vim.g.colors_name != 'sonokai' then
    return
  end
  -- ...custom hl go here ...
end

vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = "*",
  callback = sonokaiCustom
})
```

**Comment by svanharmelen** [comment]
That wasn't the real solution, but it was close enough to help me find the actual solution 😊 What was needed, was to add `nested` to the `FocusGained` autocmd:

```lua
-- Make background solid again
autocmd('FocusGained', {
  callback = function()
    vim.g.sonokai_transparent_background = 0
    vim.cmd [[ colorscheme sonokai ]]
  end,
  nested = true
})

-- Make background transparent
autocmd('FocusLost', {
  callback = function()
    vim.g.sonokai_transparent_background = 2
    vim.cmd [[ colorscheme sonokai ]]
  end,
})
```

In this case you don't want it in the `FocusLost` autocmd as then it will trigger and put back the custom colors.

Thanks for the help! Problem solved 👍🏻

**Comment by antoineco** [comment]
TIL about the `nested` attribute :)
Glad you figured in out!
