### ISSUE TITLE
xresources, base16-snazy

### ISSUE THREAD

**Issue by vlappa** [sainnhe/sonokai#99]
Nice theme, thanks. 

1) Any idea how this color scheme can be ported  to Xresources for use in terminal? 

2) I liked base16-snazzy by @chawyehsu a lot, especially for it's background I think. But there is to much red in the syntax colors (with treesitter). So now I choosed sonokai instead. Maybe it can be a inspiration for a variant. 
https://github.com/chawyehsu/base16-snazzy-scheme

**Comment by antoineco** [comment]
Regarding XResources I haven't seen any port of Sonokai, however it should be easy to adapt one of the existing ports: https://github.com/sainnhe/sonokai/wiki/Related-Projects#terminal-emulators

Regarding base16, usually the abundance of red comes from the base16 spec itself, and it is often difficult to convey the semantics of the original colorscheme through a base16 conversion. I think I did a decent job porting Everforest (another of sainnhe's colorschemes) a while ago, maybe you can take a look for inspiration: https://github.com/tinted-theming/base16-schemes/blob/main/everforest.yaml

**Comment by vlappa** [comment]
Thanks for your reply. And how do I change the background of sonokai to that from snazzy? I'm curious, I think it would be better for my eyes.

**Comment by antoineco** [comment]
snazzy uses the following color as background: https://github.com/chawyehsu/base16-snazzy-scheme/blob/6e64c88288270c9b6baf9cc7f9eb7496c39fbd0b/snazzy.yaml#L3

**Comment by antoineco** [comment]
The Vim palette can be overridden as follows: https://github.com/sainnhe/sonokai/blob/da5b10020b9ca960f5a0296ab59ccc44f0d7718e/doc/sonokai.txt#L497-L503

**Comment by vlappa** [comment]
Does the vim theme also determine the colors of the tabs? I'm not a fan of the tabs color (red like). To prominent and red is a 'alarming' color, which doesn't fit well for tabs IMHO.

**Comment by chawyehsu** [comment]
Hi @vlappa , for question of my color scheme, as @antoineco mentioned above, it is limited by the base16 spec itself that the red color is used widely. From the preview, you can see the red color is used for both variables and diff deleted. If you think it's acceptable for getting `.diff` files being rendered with colors other than red and green, you may switch them with colors you would like to use.

![image](https://github.com/sainnhe/sonokai/assets/5764917/eba10802-e429-4b44-a34b-e2b51591231e)

**Comment by chawyehsu** [comment]
> it is often difficult to convey the semantics of the original colorscheme through a base16 conversion

What I believe it is The Art of Compromise, the 16 colors constraint, I absolutely agree with you though!

**Comment by antoineco** [comment]
I've used base16 for about 3 years, mostly because it was fun at the beginning to change colorschemes in both the terminal and Vim with a single command. I eventually settled for one colorscheme which I really like, and used a "proper" version of the colorscheme where appropriate.

If you like snazzy, I couldn't recommend you more to just use proper terminal + Vim themes for snazzy. If you arrived at the point where you need to use Sonokai with a partially modified palette, you're most likely going to end up creating your own colorscheme in the end.

**Comment by antoineco** [comment]
I'm closing this because the original question was answered, but feel free to keep discussing!
